version: '3.4'

networks:
  friendsnet:

volumes:
  friendsdata:

services:

  friendssvc:
    networks:
      - friendsnet
    ports:
       - 8080:8080
    environment:
      - DB_HOST=friendsdb
    image: jsagar87/friendssvc-image

  friendsdb:
    image: postgres:9-alpine
    networks: 
      - friendsnet
    volumes:
      - friendsdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=friendsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
